### ISSUE TITLE
docs.taskcluster.net links in USAGE.md are broken

### ISSUE THREAD

**Issue by milescrabill** [taskcluster/generic-worker#197]
the links accompanying the following bullet points are broken or the pages they point to have been moved:

* Follow our [best practices][bestpractices].
* This includes [writing or updating tests][testing].
* Write a [good commit message][commit].

[bestpractices]: https://docs.taskcluster.net/docs/manual/design/devel/best-practices
[testing]: https://docs.taskcluster.net/docs/manual/design/devel/best-practices/testing
[commit]: https://docs.taskcluster.net/docs/manual/design/devel/best-practices/commits

**Comment by petemoore** [comment]
@helfi92 or @djmitche do you know what the new URLs are for these pages?

**Comment by djmitche** [comment]
They're not on the docs site anymore -- dev docs are handled in Github markdown.  See https://github.com/taskcluster/taskcluster/tree/master/dev-docs

**Comment by helfi92** [comment]
Ah. We should update those links to point to the right location.
