### ISSUE TITLE
Role Manager tool fails to create role as instructed by README

### ISSUE THREAD

**Issue by mykmelez** [taskcluster/generic-worker#53]
The generic-worker README says:

> Head over to https://tools.taskcluster.net/auth/clients/ and create yourself a clientId with permanent credentials. Then go to https://tools.taskcluster.net/auth/roles/ and create a role called client-id:<your-client-id> and give it the scope worker-developer. Keep a note of your clientId and accessToken.

And I was able to create the clientId `mozilla-ldap/myk@mozilla.com/test` using my LDAP credentials. But when I tried to create a role called `client-id:mozilla-ldap/myk@mozilla.com/test` with the scope `worker-developer`, the Role Manager complained:

> Error executing operation Error: You do not have sufficient scopes. This request requires you to have one of the following sets of scopes: [ [ "auth:create-role:client-id:mozilla-ldap/myk@mozilla.com/test" ] ] You only have the scopes: [ (a gazillion scopes) ] In other words you are missing scopes from one of the options: * Option 0: - "auth:create-role:client-id:mozilla-ldap/myk@mozilla.com/test" ---- method: createRole errorCode: InsufficientScopes statusCode: 403 time: 2017-05-02T23:57:22.805Z

I'm not sure if this is really a generic-worker issue; it might instead be a problem with the Role Manager. But since I'm following the instructions in this README, I figured I'd start by reporting the issue here.

**Comment by petemoore** [comment]
I intend to update the README.md - to advise users that they will either need to request access via the #taskcluster channel or apply for scm level 1 access, which covers the required scopes already. Users can't grant themselves scopes that they don't have - so I certainly need to update this README.

@djmitche Does this seem reasonable to you? I can't decide if this is dirtying the waters or not, but I also don't fancy the prospect of manually granting scopes to people in order for them to be able to run the generic-worker tests...

**Comment by djmitche** [comment]
A lot of our tests require scopes, so it's not unusual, but it would be nice to change that!

There are no roles starting with "client-id", so whatever instruction is indicating that myk should create such a role should be fixed.

**Comment by petemoore** [comment]
So I've decided to set the bar at having a mozillians account, by adding `assume:project:taskcluster:generic-worker-tester` to `mozillians-user:*`. I'll update the `README.md` in generic-worker shortly.

**Comment by petemoore** [comment]
Update: See https://github.com/taskcluster/taskcluster-admin/pull/4#issuecomment-299224208.

**Comment by petemoore** [comment]
Fixed in 8dccecaec95705a59147618f780dea7c1fdbbef8.
